export type PhoneCountryCode = {
  country: string;
  code: string;
  flag: {
    emoji: string;
    iso: string;
  };
};

function flag(regionCode: string) {
  return {
    emoji: regionCode.toUpperCase().replace(/./g, char => String.fromCodePoint(127397 + char.charCodeAt(0))),
    iso: regionCode.toLowerCase(),
  };
}

export const phoneCountryCodes: PhoneCountryCode[] = [
  { country: 'Afghanistan', code: '+93', flag: flag('AF') },
  { country: 'Albania', code: '+355', flag: flag('AL') },
  { country: 'Algeria', code: '+213', flag: flag('DZ') },
  { country: 'Andorra', code: '+376', flag: flag('AD') },
  { country: 'Angola', code: '+244', flag: flag('AO') },
  { country: 'Antigua and Barbuda', code: '+1-268', flag: flag('AG') },
  { country: 'Argentina', code: '+54', flag: flag('AR') },
  { country: 'Armenia', code: '+374', flag: flag('AM') },
  { country: 'Australia', code: '+61', flag: flag('AU') },
  { country: 'Austria', code: '+43', flag: flag('AT') },
  { country: 'Azerbaijan', code: '+994', flag: flag('AZ') },
  { country: 'Bahamas', code: '+1-242', flag: flag('BS') },
  { country: 'Bahrain', code: '+973', flag: flag('BH') },
  { country: 'Bangladesh', code: '+880', flag: flag('BD') },
  { country: 'Barbados', code: '+1-246', flag: flag('BB') },
  { country: 'Belarus', code: '+375', flag: flag('BY') },
  { country: 'Belgium', code: '+32', flag: flag('BE') },
  { country: 'Belize', code: '+501', flag: flag('BZ') },
  { country: 'Benin', code: '+229', flag: flag('BJ') },
  { country: 'Bhutan', code: '+975', flag: flag('BT') },
  { country: 'Bolivia', code: '+591', flag: flag('BO') },
  { country: 'Bosnia and Herzegovina', code: '+387', flag: flag('BA') },
  { country: 'Botswana', code: '+267', flag: flag('BW') },
  { country: 'Brazil', code: '+55', flag: flag('BR') },
  { country: 'Brunei', code: '+673', flag: flag('BN') },
  { country: 'Bulgaria', code: '+359', flag: flag('BG') },
  { country: 'Burkina Faso', code: '+226', flag: flag('BF') },
  { country: 'Burundi', code: '+257', flag: flag('BI') },
  { country: 'Cabo Verde', code: '+238', flag: flag('CV') },
  { country: 'Cambodia', code: '+855', flag: flag('KH') },
  { country: 'Cameroon', code: '+237', flag: flag('CM') },
  { country: 'Canada', code: '+1', flag: flag('CA') },
  { country: 'Central African Republic', code: '+236', flag: flag('CF') },
  { country: 'Chad', code: '+235', flag: flag('TD') },
  { country: 'Chile', code: '+56', flag: flag('CL') },
  { country: 'China', code: '+86', flag: flag('CN') },
  { country: 'Colombia', code: '+57', flag: flag('CO') },
  { country: 'Comoros', code: '+269', flag: flag('KM') },
  { country: 'Congo (Congo-Brazzaville)', code: '+242', flag: flag('CG') },
  { country: 'Costa Rica', code: '+506', flag: flag('CR') },
  { country: "Cote d'Ivoire", code: '+225', flag: flag('CI') },
  { country: 'Croatia', code: '+385', flag: flag('HR') },
  { country: 'Cuba', code: '+53', flag: flag('CU') },
  { country: 'Cyprus', code: '+357', flag: flag('CY') },
  { country: 'Czechia', code: '+420', flag: flag('CZ') },
  { country: 'Democratic Republic of the Congo', code: '+243', flag: flag('CD') },
  { country: 'Denmark', code: '+45', flag: flag('DK') },
  { country: 'Djibouti', code: '+253', flag: flag('DJ') },
  { country: 'Dominica', code: '+1-767', flag: flag('DM') },
  { country: 'Dominican Republic', code: '+1-809', flag: flag('DO') },
  { country: 'Ecuador', code: '+593', flag: flag('EC') },
  { country: 'Egypt', code: '+20', flag: flag('EG') },
  { country: 'El Salvador', code: '+503', flag: flag('SV') },
  { country: 'Equatorial Guinea', code: '+240', flag: flag('GQ') },
  { country: 'Eritrea', code: '+291', flag: flag('ER') },
  { country: 'Estonia', code: '+372', flag: flag('EE') },
  { country: 'Eswatini', code: '+268', flag: flag('SZ') },
  { country: 'Ethiopia', code: '+251', flag: flag('ET') },
  { country: 'Fiji', code: '+679', flag: flag('FJ') },
  { country: 'Finland', code: '+358', flag: flag('FI') },
  { country: 'France', code: '+33', flag: flag('FR') },
  { country: 'Gabon', code: '+241', flag: flag('GA') },
  { country: 'Gambia', code: '+220', flag: flag('GM') },
  { country: 'Georgia', code: '+995', flag: flag('GE') },
  { country: 'Germany', code: '+49', flag: flag('DE') },
  { country: 'Ghana', code: '+233', flag: flag('GH') },
  { country: 'Greece', code: '+30', flag: flag('GR') },
  { country: 'Grenada', code: '+1-473', flag: flag('GD') },
  { country: 'Guatemala', code: '+502', flag: flag('GT') },
  { country: 'Guinea', code: '+224', flag: flag('GN') },
  { country: 'Guinea-Bissau', code: '+245', flag: flag('GW') },
  { country: 'Guyana', code: '+592', flag: flag('GY') },
  { country: 'Haiti', code: '+509', flag: flag('HT') },
  { country: 'Honduras', code: '+504', flag: flag('HN') },
  { country: 'Hungary', code: '+36', flag: flag('HU') },
  { country: 'Iceland', code: '+354', flag: flag('IS') },
  { country: 'India', code: '+91', flag: flag('IN') },
  { country: 'Indonesia', code: '+62', flag: flag('ID') },
  { country: 'Iran', code: '+98', flag: flag('IR') },
  { country: 'Iraq', code: '+964', flag: flag('IQ') },
  { country: 'Ireland', code: '+353', flag: flag('IE') },
  { country: 'Israel', code: '+972', flag: flag('IL') },
  { country: 'Italy', code: '+39', flag: flag('IT') },
  { country: 'Jamaica', code: '+1-876', flag: flag('JM') },
  { country: 'Japan', code: '+81', flag: flag('JP') },
  { country: 'Jordan', code: '+962', flag: flag('JO') },
  { country: 'Kazakhstan', code: '+7', flag: flag('KZ') },
  { country: 'Kenya', code: '+254', flag: flag('KE') },
  { country: 'Kiribati', code: '+686', flag: flag('KI') },
  { country: 'Kuwait', code: '+965', flag: flag('KW') },
  { country: 'Kyrgyzstan', code: '+996', flag: flag('KG') },
  { country: 'Laos', code: '+856', flag: flag('LA') },
  { country: 'Latvia', code: '+371', flag: flag('LV') },
  { country: 'Lebanon', code: '+961', flag: flag('LB') },
  { country: 'Lesotho', code: '+266', flag: flag('LS') },
  { country: 'Liberia', code: '+231', flag: flag('LR') },
  { country: 'Libya', code: '+218', flag: flag('LY') },
  { country: 'Liechtenstein', code: '+423', flag: flag('LI') },
  { country: 'Lithuania', code: '+370', flag: flag('LT') },
  { country: 'Luxembourg', code: '+352', flag: flag('LU') },
  { country: 'Madagascar', code: '+261', flag: flag('MG') },
  { country: 'Malawi', code: '+265', flag: flag('MW') },
  { country: 'Malaysia', code: '+60', flag: flag('MY') },
  { country: 'Maldives', code: '+960', flag: flag('MV') },
  { country: 'Mali', code: '+223', flag: flag('ML') },
  { country: 'Malta', code: '+356', flag: flag('MT') },
  { country: 'Marshall Islands', code: '+692', flag: flag('MH') },
  { country: 'Mauritania', code: '+222', flag: flag('MR') },
  { country: 'Mauritius', code: '+230', flag: flag('MU') },
  { country: 'Mexico', code: '+52', flag: flag('MX') },
  { country: 'Micronesia', code: '+691', flag: flag('FM') },
  { country: 'Moldova', code: '+373', flag: flag('MD') },
  { country: 'Monaco', code: '+377', flag: flag('MC') },
  { country: 'Mongolia', code: '+976', flag: flag('MN') },
  { country: 'Montenegro', code: '+382', flag: flag('ME') },
  { country: 'Morocco', code: '+212', flag: flag('MA') },
  { country: 'Mozambique', code: '+258', flag: flag('MZ') },
  { country: 'Myanmar', code: '+95', flag: flag('MM') },
  { country: 'Namibia', code: '+264', flag: flag('NA') },
  { country: 'Nauru', code: '+674', flag: flag('NR') },
  { country: 'Nepal', code: '+977', flag: flag('NP') },
  { country: 'Netherlands', code: '+31', flag: flag('NL') },
  { country: 'New Zealand', code: '+64', flag: flag('NZ') },
  { country: 'Nicaragua', code: '+505', flag: flag('NI') },
  { country: 'Niger', code: '+227', flag: flag('NE') },
  { country: 'Nigeria', code: '+234', flag: flag('NG') },
  { country: 'North Korea', code: '+850', flag: flag('KP') },
  { country: 'North Macedonia', code: '+389', flag: flag('MK') },
  { country: 'Norway', code: '+47', flag: flag('NO') },
  { country: 'Oman', code: '+968', flag: flag('OM') },
  { country: 'Pakistan', code: '+92', flag: flag('PK') },
  { country: 'Palau', code: '+680', flag: flag('PW') },
  { country: 'Panama', code: '+507', flag: flag('PA') },
  { country: 'Papua New Guinea', code: '+675', flag: flag('PG') },
  { country: 'Paraguay', code: '+595', flag: flag('PY') },
  { country: 'Peru', code: '+51', flag: flag('PE') },
  { country: 'Philippines', code: '+63', flag: flag('PH') },
  { country: 'Poland', code: '+48', flag: flag('PL') },
  { country: 'Portugal', code: '+351', flag: flag('PT') },
  { country: 'Qatar', code: '+974', flag: flag('QA') },
  { country: 'Romania', code: '+40', flag: flag('RO') },
  { country: 'Russia', code: '+7', flag: flag('RU') },
  { country: 'Rwanda', code: '+250', flag: flag('RW') },
  { country: 'Saint Kitts and Nevis', code: '+1-869', flag: flag('KN') },
  { country: 'Saint Lucia', code: '+1-758', flag: flag('LC') },
  { country: 'Saint Vincent and the Grenadines', code: '+1-784', flag: flag('VC') },
  { country: 'Samoa', code: '+685', flag: flag('WS') },
  { country: 'San Marino', code: '+378', flag: flag('SM') },
  { country: 'Sao Tome and Principe', code: '+239', flag: flag('ST') },
  { country: 'Saudi Arabia', code: '+966', flag: flag('SA') },
  { country: 'Senegal', code: '+221', flag: flag('SN') },
  { country: 'Serbia', code: '+381', flag: flag('RS') },
  { country: 'Seychelles', code: '+248', flag: flag('SC') },
  { country: 'Sierra Leone', code: '+232', flag: flag('SL') },
  { country: 'Singapore', code: '+65', flag: flag('SG') },
  { country: 'Slovakia', code: '+421', flag: flag('SK') },
  { country: 'Slovenia', code: '+386', flag: flag('SI') },
  { country: 'Solomon Islands', code: '+677', flag: flag('SB') },
  { country: 'Somalia', code: '+252', flag: flag('SO') },
  { country: 'South Africa', code: '+27', flag: flag('ZA') },
  { country: 'South Korea', code: '+82', flag: flag('KR') },
  { country: 'South Sudan', code: '+211', flag: flag('SS') },
  { country: 'Spain', code: '+34', flag: flag('ES') },
  { country: 'Sri Lanka', code: '+94', flag: flag('LK') },
  { country: 'Sudan', code: '+249', flag: flag('SD') },
  { country: 'Suriname', code: '+597', flag: flag('SR') },
  { country: 'Sweden', code: '+46', flag: flag('SE') },
  { country: 'Switzerland', code: '+41', flag: flag('CH') },
  { country: 'Syria', code: '+963', flag: flag('SY') },
  { country: 'Taiwan', code: '+886', flag: flag('TW') },
  { country: 'Tajikistan', code: '+992', flag: flag('TJ') },
  { country: 'Tanzania', code: '+255', flag: flag('TZ') },
  { country: 'Thailand', code: '+66', flag: flag('TH') },
  { country: 'Timor-Leste', code: '+670', flag: flag('TL') },
  { country: 'Togo', code: '+228', flag: flag('TG') },
  { country: 'Tonga', code: '+676', flag: flag('TO') },
  { country: 'Trinidad and Tobago', code: '+1-868', flag: flag('TT') },
  { country: 'Tunisia', code: '+216', flag: flag('TN') },
  { country: 'Turkey', code: '+90', flag: flag('TR') },
  { country: 'Turkmenistan', code: '+993', flag: flag('TM') },
  { country: 'Tuvalu', code: '+688', flag: flag('TV') },
  { country: 'Uganda', code: '+256', flag: flag('UG') },
  { country: 'Ukraine', code: '+380', flag: flag('UA') },
  { country: 'United Arab Emirates', code: '+971', flag: flag('AE') },
  { country: 'United Kingdom', code: '+44', flag: flag('GB') },
  { country: 'United States', code: '+1', flag: flag('US') },
  { country: 'Uruguay', code: '+598', flag: flag('UY') },
  { country: 'Uzbekistan', code: '+998', flag: flag('UZ') },
  { country: 'Vanuatu', code: '+678', flag: flag('VU') },
  { country: 'Vatican City', code: '+379', flag: flag('VA') },
  { country: 'Venezuela', code: '+58', flag: flag('VE') },
  { country: 'Vietnam', code: '+84', flag: flag('VN') },
  { country: 'Yemen', code: '+967', flag: flag('YE') },
  { country: 'Zambia', code: '+260', flag: flag('ZM') },
  { country: 'Zimbabwe', code: '+263', flag: flag('ZW') },
  { country: 'Aland Islands', code: '+358', flag: flag('AX') },
];
